volumes:
  app-db-data:
  app-media-data:

services:
  db:
    restart: unless-stopped
    image: postgres:15-alpine
    volumes:
      - app-db-data:/var/lib/postgresql/data
    env_file:
      - .env

  backend:
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - .env
    build:
      context: .
      dockerfile: backend.dockerfile
    volumes:
      - app-media-data:/app/src/media
    ports:
      - 80:8000
