"""create file

Revision ID: 87581d255961
Revises: cdf1852f54d8
Create Date: 2022-12-11 15:24:48.614673

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '87581d255961'
down_revision = 'cdf1852f54d8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'files',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('size', sa.Integer(), nullable=False),
        sa.Column('path', sa.String(length=255), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_unique_constraint(None, 'files', ['path'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('files')
    # ### end Alembic commands ###
