"""add password

Revision ID: bc472320efcc
Revises: ad50980c7ecf
Create Date: 2022-12-24 11:02:27.330668

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = 'bc472320efcc'
down_revision = 'ad50980c7ecf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users', sa.Column('password', sa.String(length=255), nullable=False)
    )
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users',
        sa.Column(
            'hashed_password',
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
